- name: Install MySQL, RabbitMQ, and Redis on Ubuntu servers
  hosts: webservers
  become: yes
  gather_facts: yes
  vars:
    mysql_root_password: "StrongRootPass123"
    rabbitmq_user: "admin"
    rabbitmq_password: "RabbitPass123"

  tasks:

    #################################
    # Step 1: Update APT and Install Prerequisites
    #################################
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - software-properties-common
          - curl
          - gnupg
          - lsb-release
        state: present

    #################################
    # Step 2: Install MySQL
    #################################
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Ensure MySQL service is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password
      mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present

    #################################
    # Step 3: Install RabbitMQ
    #################################
    - name: Install Erlang (required for RabbitMQ)
      apt:
        name: erlang
        state: present

    - name: Add RabbitMQ repository signing key
      apt_key:
        url: https://packages.rabbitmq.com/rabbitmq-release-signing-key.asc
        state: present

    - name: Add RabbitMQ repository
      apt_repository:
        repo: "deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu $(lsb_release -cs) main"
        state: present

    - name: Install RabbitMQ server
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes

    - name: Ensure RabbitMQ service is running
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Add RabbitMQ user
      rabbitmq_user:
        user: "{{ rabbitmq_user }}"
        password: "{{ rabbitmq_password }}"
        state: present
        tags: administrator

    #################################
    # Step 4: Install Redis
    #################################
    - name: Install Redis server
      apt:
        name: redis-server
        state: present

    - name: Ensure Redis service is running
      service:
        name: redis-server
        state: started
        enabled: yes
