---
# tasks file for nginx
- name: Install Nginx package
  package:
    name: nginx
    state: present

- name: Create web root directory
  file:
    path: "{{ nginx_web_root }}"
    state: directory
    mode: '0755'
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"

- name: Place a basic index.html file
  copy:
    content: "<html><body><h1>Welcome to {{ ansible_hostname }}</h1></body></html>"
    dest: "{{ nginx_web_root }}/index.html"
    mode: '0644'
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"

- name: Configure Nginx using a template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: restart nginx  # This triggers the handler if the task changes the file

- name: Ensure Nginx is enabled and running
  service:
    name: nginx
    state: started
    enabled: yes
