---
- name: Launch an EC2 instance
  hosts: localhost
  connection: local
  collections:
    - amazon.aws

  tasks:
    - name: Launch EC2
      ec2_instance:
        name: ansible-gen-instance
        key_name: keypair_stockholms
        instance_type: t3.micro
        image_id: ami-0a716d3f3b16d290c  # Example AMI (update for your region)
        region: eu-north-1
        aws_access_key: AKIAQCJW5Q37GB6MALVW
        aws_secret_key: ONsM3XhgNAcAUR3QxyyxZQ0+a0Q/88FBUkTHAAaS
        wait: yes
      register: ec2_info

    - name: Show instance details
      debug:
        var: ec2_info
